### ISSUE TITLE
CircleTransition

### ISSUE THREAD

**Issue by maschuschu** [zhangxiaolian1991/LearnSwift#1]
Hi, and great work.

I have one question. How can i make this with more like 4 views?

Pleas help me

**Comment by suricforever** [comment]
Could you give me more info? If you want to deal with 4 circles in one view,just do like the exist one.

**Comment by suricforever** [comment]
4 views? Could you give more info about what result you want? If you want to deal with 4circles in one view, just do like the existed one . If you want to deal with 4 views in navigation controller ，this animation is navigation transition just use navigation push

**Comment by maschuschu** [comment]
i have ViewController1, viewController2, viewController3 and viewController4. But in the Circle file is only fromVC and toVC for only to views. I don't know how i can make it for other views. The viewController1 is the main controller with for buttons for each view controllers transition. I hope you know what i been :-)

**Comment by suricforever** [comment]
Sorry answer so late,  You can add a fromButton property as fromVC button in "CircleTransitionAnimator",then set different button of  CircleTransitionAnimator 's fromButton property  for different view controller
